fire:
  active: true 
electro:
  active: true 
lightning:
  active: true 
fall:    
  active: true
foodpoison:
  active: true
craftthumb:
  active: true 
cows:
  active: true
happyminer:
  active: true