update_message: true
fire:
  active: true
  message: true
  chance: 10
  chancemod: 1
  duration: 300
electro:
  active: true
  high:
    message: true
    chance: 5
    chancemod: 1
    damage: 8
  low:
    message: true
    damage: 2  
lightning:
  active: true
  skip_biome:
    - 'JUNGLE'
  message: true
  chance: 5
  chancemod: 10
  damage: 10
  cooldown: 10
fall:    
  active: true
  message: true
  duration: 5
foodpoison:
  active: true
  message: true
  chance: 10
  chancemod: 1
  multiplier: 1
  duration: 5
craftthumb:
  active: true
  message: true
  chance: 10
  chancemod: 1
  damage: 2
cows:
  active: true
  message: true
  kick:
    message: true
    damage: 4
    duration: 5
    backwards: 2
    upwards: 1
happyminer:
  active: true
  tired:
    message: true
    chance: 2
    chancemod: 1
    multiplier: 1
    duration: 10
  hunger:
    multiplier: 1
    duration: 10    
  energized:
    message: true
    chance: 2
    chancemod: 1
    multiplier: 1
    duration: 10
roses:    
  active: true
  message: true
  damage: 1
  multiplier: 3
  duration: 2
brew:
  active: false
  signs: false
  chance: 1
  chancemod: 10
  multiplier: 1
squid:
  active: true
  message: true
  chance: 25
  chancemod: 1
  multiplier: 1
  duration: 5 
tar:    
  active: true
  message: true
  multiplier: 5
  duration: 1
bow:    
  active: true
  message: true
  chance: 1
  chancemod: 1  
  damage: 4