update_message: true
fire:
  active: true
  skip_world: []
  message: true
  chance: 10
  chancemod: 1
  duration: 300
electro:
  active: true
  skip_world: []
  high:
    message: true
    chance: 5
    chancemod: 1
    damage: 8
  low:
    message: true
    damage: 2  
lightning:
  active: true
  skip_world: []
  skip_biome:
    - JUNGLE
  message: true
  chance: 5
  chancemod: 10
  damage: 10
  cooldown: 10
fall:    
  active: true
  skip_world: []
  message: true
  duration: 5
foodpoison:
  active: true
  skip_world: []
  message: true
  chance: 10
  chancemod: 1
  multiplier: 1
  duration: 5
craftthumb:
  active: true
  skip_world: []
  message: true
  chance: 10
  chancemod: 1
  damage: 2
cows:
  active: true
  skip_world: []
  message: true
  kick:
    message: true
    damage: 4
    duration: 5
    backwards: 2
    upwards: 1
happyminer:
  active: true
  skip_world: []
  tired:
    message: true
    chance: 2
    chancemod: 1
    multiplier: 1
    duration: 10
  hunger:
    multiplier: 1
    duration: 10    
  energized:
    message: true
    chance: 2
    chancemod: 1
    multiplier: 1
    duration: 10
roses:    
  active: true
  skip_world: []
  message: true
  damage: 1
  multiplier: 3
  duration: 2
brew:
  active: false
  skip_world: []
  signs: false
  chance: 1
  chancemod: 10
  multiplier: 1
squid:
  active: true
  skip_world: []
  message: true
  chance: 25
  chancemod: 1
  multiplier: 1
  duration: 5 
tar:    
  active: true
  skip_world: []
  message: true
  multiplier: 5
  duration: 1
bow:    
  active: true
  skip_world: []
  message: true
  chance: 1
  chancemod: 1  
  damage: 4
rail:
  active: true
  skip_world: []
  message: true
  chance: 1
  chancemod: 1
  distance: 1
  angle: 1
fishing:
  active: true
  skip_world: []
  lucky:
    active: true
    message: true
    chance: 5
    chancemod: 1
    items:
      - DIRT
  spawn:
    active: true
    message: true
    chance: 1
    chancemod: 1
    mobs:
      - SILVERFISH
quicksand:
  active: true
  skip_world: []
  message: true
  chance: 1
  chancemod: 1  
  cooldown: 5
  jumps: 5
desert:
  active: true
  skip_world: []
  whendesert: true
  message: true
  chance: 1
  chancemod: 1
  multiplier: 2 
boat:
  active: true
  skip_world: []
  message: true
  chance: 1
  chancemod: 1
buggyblock:
  active: true
  skip_world: []
  message: true
  chance: 100
  chancemod: 1
  blocks: []
tnt:
  active: true
  skip_world: []
  chance: 10
  chancemod: 1
ride:
  active: true
  skip_world: []
  message: true
  entitytype: []
  chance: 10
  chancemod: 1
  distance: 1
  angle: 1
worlddrop:
  active: true
  skip_world: []
  chance: 10
  chancemod: 1
  radius: 30
  abovesealvl: 20
  maxlocs: 1  
  cooldown: 900
  amount: 10 
  items:
  - APPLE
sneaky:
  active: true
  skip_world: []
zombie:
  active: true
  skip_world: []
  message: true
  whenzombie: true
  chance: 10
  chancemod: 1
heavy:
  active: true
  skip_world: []
  walkspeed: 0.1
  flyspeed: 0.2
  modifier: 1.0