name: ijmh
description: "It Just Might Happen" is reality added based on events
author: nsordk & PlugMania
main: info.plugmania.ijmh.ijmh
version: 1.0.0
permissions:
  ijmh.immunity.*:
    description: Immunity to all events
  ijmh.immunity.fire:
    description: Immunity to catching fire on use of flint & tinder.
  ijmh.immunity.fall:
    description: Immunity to concussion on fall.
  ijmh.immunity.foodpoison:
    description: Immunity to getting foodpoisoning when eating.
  ijmh.immunity.lightning:
    description: Immunity to getting hit by Lightning while under trees.
  ijmh.immunity.electro:
    description: Immunity to getting electrocuted when touching blocks powered by redstone.
              