name: ijmh
description: -It Just Might Happen- is reality added based on events
author: nsordk & PlugMania
main: info.plugmania.ijmh.ijmh
version: 2.1.1
commands:
  ijmh:
    usage: /ijmh
    description: gives access to toggle effects on/off.
permissions:
  ijmh.immunity.*:
    description: Immunity to all events
    default: false
  ijmh.immunity.fire:
    description: Immunity to catching fire on use of flint & tinder.
    default: false
  ijmh.immunity.fall:
    description: Immunity to concussion on fall.
    default: false
  ijmh.immunity.foodpoison:
    description: Immunity to getting foodpoisoning when eating.
    default: false
  ijmh.immunity.lightning:
    description: Immunity to getting hit by Lightning while under trees.
    default: false
  ijmh.immunity.electro:
    description: Immunity to getting electrocuted when touching blocks powered by redstone.
    default: false
  ijmh.immunity.craftthumb:
    description: Immunity to your thumb being victim while crafting.
    default: false  
  ijmh.immunity.cowskick:
    description: Immunity to cows kicking from behind.
    default: false
  ijmh.immunity.tiredminer:
    description: Immunity effect occuring when mining makes you tired.
    default: false
  ijmh.immunity.roses:
    description: Immunity to damage and slowing from roses.
    default: false
  ijmh.immunity.bow:
    description: Immunity to bow breaking in pvp.
    default: false
  ijmh.immunity.rail:
    description: Immunity to getting thrown off rails.
    default: false
  ijmh.immunity.spawn:
    description: Immunity to catching mobs while fishing.
    default: false 
  ijmh.immunity.quicksand:
    description: Immunity to be effected by quicksand.
    default: false
  ijmh.immunity.desert:
    description: Immunity getting thirsty when in the sunny desert.
    default: false 
  ijmh.immunity.boat:
    description: Immunity to boats sinking and player getting stuck to drown.
    default: false
  ijmh.immunity.tnt:
    description: Immunity to unstable explosion and get killed from it when placing tnt.
    default: false
  ijmh.immunity.ride:
    description: Immunity to entity's going wild when riding them.
    default: false
  ijmh.immunity.sneaky:
    description: Immunity from having to sneak in order to loot.
    default: false
  ijmh.immunity.heavy:
    description: Immunity from becoming slower with armor on.
    default: false 
  ijmh.admin:
    description: Grant access to the toggle event.
    default: op